# Spot Gamma Levels - SPY
# Generated by the spot-gamma engine. Levels are display inputs only; the
# Python engine is the source of truth. Regenerate when the chain updates.
# spot=585.00  net_gex=4.046e+07  regime=positive

input zeroGamma = 584.21;
input callWall = 600.00;
input putWall = 570.00;
input volTrigger = 585.00;

plot ZeroGammaLine = zeroGamma;
plot CallWallLine = callWall;
plot PutWallLine = putWall;
plot VolTriggerLine = volTrigger;

ZeroGammaLine.SetDefaultColor(Color.YELLOW);
ZeroGammaLine.SetStyle(Curve.SHORT_DASH);
CallWallLine.SetDefaultColor(Color.RED);
CallWallLine.SetStyle(Curve.FIRM);
PutWallLine.SetDefaultColor(Color.GREEN);
PutWallLine.SetStyle(Curve.FIRM);
VolTriggerLine.SetDefaultColor(Color.CYAN);
VolTriggerLine.SetStyle(Curve.LONG_DASH);

AddLabel(yes, "SPY regime: positive", Color.GREEN);
AddLabel(yes, "Zero Gamma: " + zeroGamma, Color.YELLOW);
AddLabel(yes, "Call Wall: " + callWall, Color.RED);
AddLabel(yes, "Put Wall: " + putWall, Color.GREEN);
AddLabel(yes, "Vol Trigger: " + volTrigger, Color.CYAN);
