# Spot Gamma Levels - QQQ
# Generated by the spot-gamma engine. Levels are display inputs only; the
# Python engine is the source of truth. Regenerate when the chain updates.
# spot=498.00  net_gex=2.542e+07  regime=positive

input zeroGamma = 497.36;
input callWall = 510.50;
input putWall = 488.00;
input volTrigger = 498.00;

plot ZeroGammaLine = zeroGamma;
plot CallWallLine = callWall;
plot PutWallLine = putWall;
plot VolTriggerLine = volTrigger;

ZeroGammaLine.SetDefaultColor(Color.YELLOW);
ZeroGammaLine.SetStyle(Curve.SHORT_DASH);
CallWallLine.SetDefaultColor(Color.RED);
CallWallLine.SetStyle(Curve.FIRM);
PutWallLine.SetDefaultColor(Color.GREEN);
PutWallLine.SetStyle(Curve.FIRM);
VolTriggerLine.SetDefaultColor(Color.CYAN);
VolTriggerLine.SetStyle(Curve.LONG_DASH);

AddLabel(yes, "QQQ regime: positive", Color.GREEN);
AddLabel(yes, "Zero Gamma: " + zeroGamma, Color.YELLOW);
AddLabel(yes, "Call Wall: " + callWall, Color.RED);
AddLabel(yes, "Put Wall: " + putWall, Color.GREEN);
AddLabel(yes, "Vol Trigger: " + volTrigger, Color.CYAN);
