# Spot Gamma Levels - SPX
# Generated by the spot-gamma engine. Levels are display inputs only; the
# Python engine is the source of truth. Regenerate when the chain updates.
# spot=5850.00  net_gex=3.777e+08  regime=positive

input zeroGamma = 5842.10;
input callWall = 6000.00;
input putWall = 5700.00;
input volTrigger = 5850.00;

plot ZeroGammaLine = zeroGamma;
plot CallWallLine = callWall;
plot PutWallLine = putWall;
plot VolTriggerLine = volTrigger;

ZeroGammaLine.SetDefaultColor(Color.YELLOW);
ZeroGammaLine.SetStyle(Curve.SHORT_DASH);
CallWallLine.SetDefaultColor(Color.RED);
CallWallLine.SetStyle(Curve.FIRM);
PutWallLine.SetDefaultColor(Color.GREEN);
PutWallLine.SetStyle(Curve.FIRM);
VolTriggerLine.SetDefaultColor(Color.CYAN);
VolTriggerLine.SetStyle(Curve.LONG_DASH);

AddLabel(yes, "SPX regime: positive", Color.GREEN);
AddLabel(yes, "Zero Gamma: " + zeroGamma, Color.YELLOW);
AddLabel(yes, "Call Wall: " + callWall, Color.RED);
AddLabel(yes, "Put Wall: " + putWall, Color.GREEN);
AddLabel(yes, "Vol Trigger: " + volTrigger, Color.CYAN);
