# Spot Gamma Levels - QQQ
# Generated by the spot-gamma engine. Levels are display inputs only; the
# Python engine is the source of truth. Regenerate when the chain updates.
# spot=737.65  net_gex=4.736e+09  regime=positive  0DTE=23%

input callWall = 738.00;
input putWall = 660.00;
input zeroGamma = 724.57;
input volTrigger = 725.00;
input absGamma = 738.00;
input hedgeWall = 738.00;
input showFlipZone = yes;
input showRegimeBackground = yes;
input enableAlerts = no;

# --- Levels as horizontal lines -------------------------------------------
plot CallWallLine = callWall;
plot PutWallLine = putWall;
plot ZeroGammaLine = zeroGamma;
plot VolTriggerLine = volTrigger;
plot AbsGammaLine = absGamma;
plot HedgeWallLine = hedgeWall;

CallWallLine.SetDefaultColor(CreateColor(46, 211, 144));
CallWallLine.SetStyle(Curve.FIRM);
CallWallLine.SetLineWeight(2);
PutWallLine.SetDefaultColor(CreateColor(255, 82, 105));
PutWallLine.SetStyle(Curve.FIRM);
PutWallLine.SetLineWeight(2);
ZeroGammaLine.SetDefaultColor(CreateColor(245, 177, 76));
ZeroGammaLine.SetStyle(Curve.SHORT_DASH);
VolTriggerLine.SetDefaultColor(CreateColor(180, 135, 255));
VolTriggerLine.SetStyle(Curve.LONG_DASH);
AbsGammaLine.SetDefaultColor(CreateColor(54, 199, 224));
AbsGammaLine.SetStyle(Curve.SHORT_DASH);
HedgeWallLine.SetDefaultColor(CreateColor(255, 157, 77));
HedgeWallLine.SetStyle(Curve.SHORT_DASH);

# --- Flip zone: shaded band between Gamma Flip and Vol Trigger -------------
# The transition region where dealer hedging flips from dampening to amplifying.
plot FlipHi = if showFlipZone then Max(zeroGamma, volTrigger) else Double.NaN;
plot FlipLo = if showFlipZone then Min(zeroGamma, volTrigger) else Double.NaN;
FlipHi.SetDefaultColor(CreateColor(245, 177, 76));
FlipLo.SetDefaultColor(CreateColor(245, 177, 76));
FlipHi.HideTitle();
FlipLo.HideTitle();
AddCloud(FlipHi, FlipLo, CreateColor(60, 45, 20), CreateColor(60, 45, 20));

# --- Regime background -----------------------------------------------------
# Positive gamma (mean-reverting) tints green; negative (trending) tints red.
DefineGlobalColor("RegimeBg", CreateColor(10, 30, 22));
AssignBackgroundColor(if showRegimeBackground then GlobalColor("RegimeBg") else Color.CURRENT);

# --- Dashboard labels ------------------------------------------------------
AddLabel(yes, "QQQ  POSITIVE GAMMA", Color.GREEN);
AddLabel(yes, "Net GEX/1%: $4.7B", Color.GREEN);
AddLabel(yes, "0DTE: 23%", CreateColor(91, 140, 255));
AddLabel(yes, "Call Wall " + callWall, CreateColor(46, 211, 144));
AddLabel(yes, "Hedge Wall " + hedgeWall, CreateColor(255, 157, 77));
AddLabel(yes, "Vol Trigger " + volTrigger, CreateColor(180, 135, 255));
AddLabel(yes, "Gamma Flip " + zeroGamma, CreateColor(245, 177, 76));
AddLabel(yes, "Abs Gamma " + absGamma, CreateColor(54, 199, 224));
AddLabel(yes, "Put Wall " + putWall, CreateColor(255, 82, 105));

# --- Alert conditions ------------------------------------------------------
# Fire once per bar when price crosses a key level (chart alerts must be armed
# in TOS; enableAlerts gates them so the study is quiet by default).
def crossedCall = Crosses(close, callWall, CrossingDirection.ANY);
def crossedPut = Crosses(close, putWall, CrossingDirection.ANY);
def crossedFlip = Crosses(close, zeroGamma, CrossingDirection.ANY);
Alert(enableAlerts and crossedCall, "QQQ testing Call Wall", Alert.BAR, Sound.Ding);
Alert(enableAlerts and crossedPut, "QQQ testing Put Wall", Alert.BAR, Sound.Ding);
Alert(enableAlerts and crossedFlip, "QQQ crossing Gamma Flip", Alert.BAR, Sound.Chimes);
