"""Render finished gamma levels as a Thinkorswim study.

ThinkScript is a *display* layer only: it cannot ingest a live chain. We emit a
study whose ``input`` values are the engine's computed levels, so the trader
pastes (or the dashboard regenerates) the numbers and Thinkorswim draws the
horizontal lines and labels.
"""

from __future__ import annotations

from .models import GammaLevels

_TEMPLATE = """# Spot Gamma Levels - {symbol}
# Generated by the spot-gamma engine. Levels are display inputs only; the
# Python engine is the source of truth. Regenerate when the chain updates.
# spot={spot:.2f}  net_gex={net_gex:.3e}  regime={regime}

input zeroGamma = {zero_gamma};
input callWall = {call_wall};
input putWall = {put_wall};
input volTrigger = {vol_trigger};

plot ZeroGammaLine = zeroGamma;
plot CallWallLine = callWall;
plot PutWallLine = putWall;
plot VolTriggerLine = volTrigger;

ZeroGammaLine.SetDefaultColor(Color.YELLOW);
ZeroGammaLine.SetStyle(Curve.SHORT_DASH);
CallWallLine.SetDefaultColor(Color.RED);
CallWallLine.SetStyle(Curve.FIRM);
PutWallLine.SetDefaultColor(Color.GREEN);
PutWallLine.SetStyle(Curve.FIRM);
VolTriggerLine.SetDefaultColor(Color.CYAN);
VolTriggerLine.SetStyle(Curve.LONG_DASH);

AddLabel(yes, "{symbol} regime: {regime}", {regime_color});
AddLabel(yes, "Zero Gamma: " + zeroGamma, Color.YELLOW);
AddLabel(yes, "Call Wall: " + callWall, Color.RED);
AddLabel(yes, "Put Wall: " + putWall, Color.GREEN);
AddLabel(yes, "Vol Trigger: " + volTrigger, Color.CYAN);
"""


def _fmt(value: float | None) -> str:
    """ThinkScript inputs must be numeric; use 0 as a neutral placeholder when
    a level could not be computed (the label still renders, reading 0)."""
    return f"{value:.2f}" if value is not None else "0"


def render_thinkscript(levels: GammaLevels) -> str:
    regime_color = "Color.GREEN" if levels.regime == "positive" else "Color.RED"
    return _TEMPLATE.format(
        symbol=levels.symbol,
        spot=levels.spot,
        net_gex=levels.net_gex,
        regime=levels.regime,
        regime_color=regime_color,
        zero_gamma=_fmt(levels.zero_gamma),
        call_wall=_fmt(levels.call_wall),
        put_wall=_fmt(levels.put_wall),
        vol_trigger=_fmt(levels.volatility_trigger),
    )
