"""Render finished gamma levels as a Thinkorswim study.

ThinkScript is a *display* layer only: it cannot ingest a live chain. We emit a
study whose ``input`` values are the engine's computed levels, so the trader
pastes (or the dashboard regenerates) the numbers and Thinkorswim draws the
lines, labels, a flip-zone cloud, a color-coded regime background, and alerts.

Colors are kept in sync with the dashboard ($lib/levels): Call Wall green,
Put Wall red, Gamma Flip orange, Vol Trigger violet, Abs Gamma cyan,
Hedge Wall orange.
"""

from __future__ import annotations

from .models import GammaLevels

_TEMPLATE = """# Spot Gamma Levels - {symbol}
# Generated by the spot-gamma engine. Levels are display inputs only; the
# Python engine is the source of truth. Regenerate when the chain updates.
# spot={spot:.2f}  net_gex={net_gex:.3e}  regime={regime}  0DTE={zero_dte_pct:.0f}%

input callWall = {call_wall};
input putWall = {put_wall};
input zeroGamma = {zero_gamma};
input volTrigger = {vol_trigger};
input absGamma = {abs_gamma};
input hedgeWall = {hedge_wall};
input showFlipZone = yes;
input showRegimeBackground = yes;
input enableAlerts = no;

# --- Levels as horizontal lines -------------------------------------------
plot CallWallLine = callWall;
plot PutWallLine = putWall;
plot ZeroGammaLine = zeroGamma;
plot VolTriggerLine = volTrigger;
plot AbsGammaLine = absGamma;
plot HedgeWallLine = hedgeWall;

CallWallLine.SetDefaultColor(CreateColor(46, 211, 144));
CallWallLine.SetStyle(Curve.FIRM);
CallWallLine.SetLineWeight(2);
PutWallLine.SetDefaultColor(CreateColor(255, 82, 105));
PutWallLine.SetStyle(Curve.FIRM);
PutWallLine.SetLineWeight(2);
ZeroGammaLine.SetDefaultColor(CreateColor(245, 177, 76));
ZeroGammaLine.SetStyle(Curve.SHORT_DASH);
VolTriggerLine.SetDefaultColor(CreateColor(180, 135, 255));
VolTriggerLine.SetStyle(Curve.LONG_DASH);
AbsGammaLine.SetDefaultColor(CreateColor(54, 199, 224));
AbsGammaLine.SetStyle(Curve.SHORT_DASH);
HedgeWallLine.SetDefaultColor(CreateColor(255, 157, 77));
HedgeWallLine.SetStyle(Curve.SHORT_DASH);

# --- Flip zone: shaded band between Gamma Flip and Vol Trigger -------------
# The transition region where dealer hedging flips from dampening to amplifying.
plot FlipHi = if showFlipZone then Max(zeroGamma, volTrigger) else Double.NaN;
plot FlipLo = if showFlipZone then Min(zeroGamma, volTrigger) else Double.NaN;
FlipHi.SetDefaultColor(CreateColor(245, 177, 76));
FlipLo.SetDefaultColor(CreateColor(245, 177, 76));
FlipHi.HideTitle();
FlipLo.HideTitle();
AddCloud(FlipHi, FlipLo, CreateColor(60, 45, 20), CreateColor(60, 45, 20));

# --- Regime background -----------------------------------------------------
# Positive gamma (mean-reverting) tints green; negative (trending) tints red.
DefineGlobalColor("RegimeBg", {regime_bg});
AssignBackgroundColor(if showRegimeBackground then GlobalColor("RegimeBg") else Color.CURRENT);

# --- Dashboard labels ------------------------------------------------------
AddLabel(yes, "{symbol}  {regime_text}", {regime_color});
AddLabel(yes, "Net GEX/1%: {net_gex_human}", {regime_color});
AddLabel(yes, "0DTE: {zero_dte_pct:.0f}%", CreateColor(91, 140, 255));
AddLabel(yes, "Call Wall " + callWall, CreateColor(46, 211, 144));
AddLabel(yes, "Hedge Wall " + hedgeWall, CreateColor(255, 157, 77));
AddLabel(yes, "Vol Trigger " + volTrigger, CreateColor(180, 135, 255));
AddLabel(yes, "Gamma Flip " + zeroGamma, CreateColor(245, 177, 76));
AddLabel(yes, "Abs Gamma " + absGamma, CreateColor(54, 199, 224));
AddLabel(yes, "Put Wall " + putWall, CreateColor(255, 82, 105));

# --- Alert conditions ------------------------------------------------------
# Fire once per bar when price crosses a key level (chart alerts must be armed
# in TOS; enableAlerts gates them so the study is quiet by default).
def crossedCall = Crosses(close, callWall, CrossingDirection.ANY);
def crossedPut = Crosses(close, putWall, CrossingDirection.ANY);
def crossedFlip = Crosses(close, zeroGamma, CrossingDirection.ANY);
Alert(enableAlerts and crossedCall, "{symbol} testing Call Wall", Alert.BAR, Sound.Ding);
Alert(enableAlerts and crossedPut, "{symbol} testing Put Wall", Alert.BAR, Sound.Ding);
Alert(enableAlerts and crossedFlip, "{symbol} crossing Gamma Flip", Alert.BAR, Sound.Chimes);
"""


def _fmt(value: float | None) -> str:
    """ThinkScript inputs must be numeric; use 0 as a neutral placeholder when
    a level could not be computed (the label still renders, reading 0)."""
    return f"{value:.2f}" if value is not None else "0"


def _human_gex(value: float) -> str:
    """Compact dollar GEX, e.g. 9.38e10 -> '$93.8B' (matches the dashboard)."""
    sign = "-" if value < 0 else ""
    a = abs(value)
    if a >= 1e9:
        return f"{sign}${a / 1e9:.1f}B"
    if a >= 1e6:
        return f"{sign}${a / 1e6:.1f}M"
    if a >= 1e3:
        return f"{sign}${a / 1e3:.1f}K"
    return f"{sign}${a:.0f}"


def render_thinkscript(levels: GammaLevels) -> str:
    positive = levels.regime == "positive"
    return _TEMPLATE.format(
        symbol=levels.symbol,
        spot=levels.spot,
        net_gex=levels.net_gex,
        net_gex_human=_human_gex(levels.net_gex),
        regime=levels.regime,
        regime_text=("POSITIVE GAMMA" if positive else "NEGATIVE GAMMA"),
        regime_color=("Color.GREEN" if positive else "Color.RED"),
        # subtle tints (R,G,B) — green for positive/pinning, red for negative/trending
        regime_bg=("CreateColor(10, 30, 22)" if positive else "CreateColor(36, 14, 18)"),
        zero_dte_pct=levels.zero_dte_share * 100,
        call_wall=_fmt(levels.call_wall),
        put_wall=_fmt(levels.put_wall),
        zero_gamma=_fmt(levels.zero_gamma),
        vol_trigger=_fmt(levels.volatility_trigger),
        abs_gamma=_fmt(levels.absolute_gamma),
        hedge_wall=_fmt(levels.hedge_wall),
    )
